# Version of docker-compose
version: '3'
# 
services:    
  db:
    image: postgres:11.2-alpine
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_USER=mitchel
      - POSTGRES_PASS=mitchel
      - POSTGRES_DBNAME=cakes
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the three specified below
      #- POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
    ports:
      - 5434:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"
  phoenix:    
    build: .      
    environment:
      # Variables to connect to our Postgres server
      PGUSER: mitchel
      PGPASSWORD: mitchel
      PGDATABASE: cakes
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: db         
    volumes:
      - .:/app
    ports:      
      - "4000:4000"
    depends_on:      
      - db
# Define the volumes
volumes:
  postgres-data:
